### ISSUE TITLE
Modification for python3

### ISSUE THREAD

**Issue by oe2lsp** [simonyiszk/openwebrx#137]
according to https://pythonclock.org/ python2[.7] is going to be retired at the end of the year. Is there any way we can get an python3 compatible version of the great openwebrx?

thanks
Lucas

**Comment by ha7ilm** [comment]
Yes, I plan to finish porting OpenWebRX to Python 3 by that time.

**Comment by oe2lsp** [comment]
great to hear!

**Comment by jketterl** [comment]
I have taken an afternoon and ported the original code over to python 3 here: https://github.com/jketterl/openwebrx/tree/python3

I made it to the point where it seems to be mostly working, but it certainly can use some more testing.

Also, this is not downwards compatible. I doubt that it is possible without plenty of overhead... but since python 2 should be close to it's end, I don't think it's much of a problem.

**Comment by D0han** [comment]
I have been running @jketterl version under py3 for months already, can recommend.

**Comment by jketterl** [comment]
@D0han that's not the version I linked above. This is a python3 port of the original code.

**Comment by ha7ilm** [comment]
> I have taken an afternoon and ported the original code over to python 3 here: https://github.com/jketterl/openwebrx/tree/python3

Thanks, I'll take a look.

**Comment by ha7ilm** [comment]
> > I have taken an afternoon and ported the original code over to python 3 here: https://github.com/jketterl/openwebrx/tree/python3
> 
> Thanks, I'll take a look.

In the meantime, I've decided to discontinue the whole project, so I don't plan to support Python 3 myself. On this reason, I'm closing this.
